services:
  - type: web
    name: django-app
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y tesseract-ocr libtesseract-dev build-essential gcc && \
      apt-get clean && \
      rm -rf /var/lib/apt/lists/* && \
      pip install -r requirements.txt
    startCommand: |
      python manage.py migrate && \
      gunicorn agritech.wsgi:application --bind 0.0.0.0:8000 --workers 3 --threads 2
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-secret-key
      - key: CLOUDINARY_URL
        value: cloudinary://api_key:api_secret@cloud_name