# Generated by Django 5.1.4 on 2024-12-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageprocessor', '0002_alter_uploadedimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='farmer_id',
            field=models.CharField(max_length=255),
        ),
    ]
